codecov:
  require_ci_to_pass: true
coverage:
  status:
    project:
      default:
        target: 80
        only_pulls: true
        informational: true
      cc:
        paths:
          - src/main/cc
      python:
        paths:
          - src/main/python
      kotlin:
        paths:
          - src/main/kotlin
  status:
    patch:
      default:
        target: 80
        only_pulls: true
        informational: true
      cc:
        paths:
          - src/main/cc
      python:
        paths:
          - src/main/python
      kotlin:
        paths:
          - src/main/kotlin
comment:
  layout: " diff, flags, files"
  behavior: default
  hide_project_coverage: false