name: coverage

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'
    types: [opened, synchronize, edited]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: coverage
    runs-on: ubuntu-22.04
    env:
      CLUSTER_LOGS_PATH: cluster-logs
    steps:
      - name: Check out revision
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: world-federation-of-advertisers/actions/setup-bazel@v2

      - name: Build
        run: >
          bazel build --worker_quit_after_build
          //...

      - name: Run tests
        id: run-tests
        run: bazel coverage --instrumentation_filter="//src/main/...,-@.*"  --nocache_test_results --combined_report=lcov //...

      - name: Bazel output path
        run: echo "BAZEL_OUTPUT_PATH=$(bazel info output_path)" >> $GITHUB_ENV

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{ env.BAZEL_OUTPUT_PATH }}/_coverage/_coverage_report.dat  

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: laureanobrs/test-bazel-cov
          files: ${{ env.BAZEL_OUTPUT_PATH }}/_coverage/_coverage_report.dat
